development:
  secret_key_base: AIzaSyCfk9KoyDySjb_5NeqX6bu3m7z1VnnSP6Q
  google_client_id: 26374530676-m2jm76jh7gtv0rrc7k2csrrufp28taom.apps.googleusercontent.com
  google_client_secret: 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